(function(){
"use strict";
var CONFIG_KEY="seduc2026_cloud_config_v1",LAST_SYNC_KEY="seduc2026_cloud_last_sync_v1",AUTH_KEY="seduc2026_legacy_auth_v1";
var cloudDialog=document.getElementById("cloudDialog"),cloudBtn=document.getElementById("cloudBtn"),stateBox=document.getElementById("cloudStateBox"),statusText=document.getElementById("cloudStatusText"),userText=document.getElementById("cloudUserText");
var currentSession=null,syncTimer=null,reconciling=false,suppressSync=false;
function meaningful(s){if(!s)return false;return Object.keys(s.sessions||{}).length>0||(s.fragilities||[]).length>0||Object.keys(s.simulations||{}).length>0||(s.bankAttempts||[]).length>0;}
state.meta=state.meta||{};if(!state.meta.updatedAt){state.meta.updatedAt=meaningful(state)?new Date().toISOString():"1970-01-01T00:00:00.000Z";localStorage.setItem(STATE_KEY,JSON.stringify(state));}
var originalSave=save;save=function(){state.meta=state.meta||{};state.meta.updatedAt=new Date().toISOString();originalSave();if(!suppressSync)queueSync();};
function bundledConfig(){var x=window.SEDUC_CLOUD_CONFIG||{};return{url:String(x.supabaseUrl||"").replace(/\s+/g,"").replace(/\/$/,""),key:String(x.supabaseAnonKey||"").replace(/\s+/g,"")};}
function localConfig(){try{return JSON.parse(localStorage.getItem(CONFIG_KEY)||"{}");}catch(e){return{};}}
function getConfig(){var l=localConfig(),b=bundledConfig();return{url:String(l.url||b.url||"").replace(/\/$/,""),key:String(l.key||b.key||"")};}
function configured(){var c=getConfig();return /^https:\/\//.test(c.url)&&!!c.key;}
function authLoad(){try{return JSON.parse(localStorage.getItem(AUTH_KEY)||"null");}catch(e){return null;}}
function authSave(s){currentSession=s||null;if(s)localStorage.setItem(AUTH_KEY,JSON.stringify(s));else localStorage.removeItem(AUTH_KEY);}
function user(){return currentSession&&currentSession.user?currentSession.user:null;} function token(){return currentSession&&currentSession.access_token?currentSession.access_token:"";}
function setCloudState(kind,title,subtitle){if(cloudBtn){cloudBtn.setAttribute("data-cloud",kind);cloudBtn.title=title+(subtitle?" — "+subtitle:"");}if(stateBox)stateBox.setAttribute("data-state",kind);if(statusText)statusText.textContent=title;if(userText)userText.textContent=subtitle||"";}
function fillConfigFields(){var c=getConfig(),u=document.getElementById("cloudUrl"),k=document.getElementById("cloudKey"),d=document.getElementById("cloudConfigDetails"),b=bundledConfig();if(u)u.value=c.url;if(k)k.value=c.key;if(d&&b.url&&b.key)d.open=false;}
function showAuthUI(){var logged=!!user(),a=document.getElementById("cloudLogin"),b=document.getElementById("cloudSignup"),c=document.getElementById("cloudLogout"),e=document.getElementById("cloudEmail"),p=document.getElementById("cloudPassword");if(a)a.hidden=logged;if(b)b.hidden=logged;if(c)c.hidden=!logged;if(e){e.disabled=logged;if(logged)e.value=user().email||"";}if(p)p.disabled=logged;}
function xhr(method,url,body,headers,cb){var c=getConfig(),x=new XMLHttpRequest();x.open(method,url,true);x.setRequestHeader("apikey",c.key);x.setRequestHeader("Content-Type","application/json");if(token())x.setRequestHeader("Authorization","Bearer "+token());if(headers)for(var h in headers)if(Object.prototype.hasOwnProperty.call(headers,h))x.setRequestHeader(h,headers[h]);x.onreadystatechange=function(){if(x.readyState!==4)return;var data=null;try{data=x.responseText?JSON.parse(x.responseText):null;}catch(e){data=x.responseText;}if(x.status>=200&&x.status<300)cb(null,data,x);else cb(new Error((data&&data.message)||(data&&data.error_description)||(data&&data.error)||("HTTP "+x.status)),data,x);};x.onerror=function(){cb(new Error("Falha de rede."));};x.send(body===null||body===undefined?null:JSON.stringify(body));}
function refreshIfNeeded(cb){if(!currentSession||!currentSession.refresh_token){cb();return;}var exp=Number(currentSession.expires_at||0)*1000;if(exp&&Date.now()<exp-60000){cb();return;}var c=getConfig();xhr("POST",c.url+"/auth/v1/token?grant_type=refresh_token",{refresh_token:currentSession.refresh_token},null,function(err,data){if(!err&&data&&data.access_token){data.expires_at=Math.floor(Date.now()/1000)+Number(data.expires_in||3600);authSave(data);showAuthUI();}cb(err);});}
function login(email,password,cb){var c=getConfig();xhr("POST",c.url+"/auth/v1/token?grant_type=password",{email:email,password:password},null,function(err,data){if(!err&&data&&data.access_token){data.expires_at=Math.floor(Date.now()/1000)+Number(data.expires_in||3600);authSave(data);showAuthUI();}cb(err,data);});}
function signup(email,password,cb){var c=getConfig();xhr("POST",c.url+"/auth/v1/signup",{email:email,password:password},null,function(err,data){if(!err&&data&&data.access_token){data.expires_at=Math.floor(Date.now()/1000)+Number(data.expires_in||3600);authSave(data);showAuthUI();}cb(err,data);});}
function queueSync(){if(!user())return;clearTimeout(syncTimer);syncTimer=setTimeout(function(){pushCloud();},900);}
function pushCloud(done){done=done||function(){};if(!user()){done(false);return;}if(navigator.onLine===false){setCloudState("offline","Alterações salvas no aparelho","Aguardando internet.");done(false);return;}setCloudState("syncing","Sincronizando…",user().email||"");refreshIfNeeded(function(re){if(re){setCloudState("error","Sessão expirada","Entre novamente.");done(false);return;}var c=getConfig(),payload=JSON.parse(JSON.stringify(state));payload.meta=payload.meta||{};payload.meta.updatedAt=payload.meta.updatedAt||new Date().toISOString();xhr("POST",c.url+"/rest/v1/study_state?on_conflict=user_id",{user_id:user().id,payload:payload,updated_at:payload.meta.updatedAt},{"Prefer":"resolution=merge-duplicates,return=minimal"},function(err){if(err){setCloudState("error","Falha ao sincronizar",err.message);done(false);return;}localStorage.setItem(LAST_SYNC_KEY,new Date().toISOString());setCloudState("synced","Sincronizado",(user().email||"Conta")+" • "+new Date().toLocaleTimeString());done(true);});});}
function readCloud(cb){if(!user()){cb(null,null);return;}refreshIfNeeded(function(re){if(re){cb(re);return;}var c=getConfig();xhr("GET",c.url+"/rest/v1/study_state?select=payload,updated_at&user_id=eq."+encodeURIComponent(user().id)+"&limit=1",null,null,function(err,data){if(err){cb(err);return;}cb(null,data&&data.length?data[0]:null);});});}
function replaceLocal(next){suppressSync=true;state=next||{};state.sessions=state.sessions||{};state.fragilities=state.fragilities||[];state.simulations=state.simulations||{};state.bankAttempts=state.bankAttempts||[];state.questionBank=state.questionBank||[];state.meta=state.meta||{};localStorage.setItem(STATE_KEY,JSON.stringify(state));renderAll();suppressSync=false;}
function reconcile(){if(reconciling||!user()||navigator.onLine===false)return;reconciling=true;readCloud(function(err,remote){if(err){setCloudState("error","Falha ao ler a nuvem",err.message);reconciling=false;return;}if(!remote){pushCloud(function(){reconciling=false;});return;}var cloudState=remote.payload||{},localHas=meaningful(state),cloudHas=meaningful(cloudState),localT=Date.parse((state.meta&&state.meta.updatedAt)||0)||0,cloudT=Date.parse((cloudState.meta&&cloudState.meta.updatedAt)||remote.updated_at||0)||0;if(cloudHas&&(!localHas||cloudT>localT+500)){replaceLocal(cloudState);setCloudState("synced","Dados baixados da nuvem",user().email||"");reconciling=false;}else if(localHas&&(!cloudHas||localT>cloudT+500)){pushCloud(function(){reconciling=false;});}else{setCloudState("synced","Sincronizado",user().email||"");reconciling=false;}});}
function forcePull(){if(!user()){toast("Entre na nuvem primeiro.");return;}readCloud(function(err,remote){if(err){toast(err.message);return;}if(!remote||!remote.payload){toast("Ainda não há dados na nuvem.");return;}if(meaningful(state)&&!confirm("Substituir os dados deste iPad pela versão da nuvem?"))return;replaceLocal(remote.payload);toast("Versão da nuvem carregada.");setCloudState("synced","Dados baixados da nuvem",user().email||"");});}
fillConfigFields();currentSession=authLoad();showAuthUI();if(user()){setCloudState("syncing","Conectado • verificando",user().email||"");reconcile();}else if(configured())setCloudState("local","Nuvem pronta","Entre com a mesma conta usada no celular.");else setCloudState("local","Modo local","Configure o Supabase.");
if(cloudBtn)cloudBtn.onclick=function(){fillConfigFields();if(cloudDialog&&cloudDialog.showModal)cloudDialog.showModal();else if(cloudDialog){cloudDialog.setAttribute("open","");cloudDialog.style.display="block";}};
var close=document.getElementById("closeCloudDialog");if(close)close.onclick=function(){if(cloudDialog&&cloudDialog.close)cloudDialog.close();else if(cloudDialog){cloudDialog.removeAttribute("open");cloudDialog.style.display="none";}};
var saveCfg=document.getElementById("cloudSaveConfig");if(saveCfg)saveCfg.onclick=function(){var url=document.getElementById("cloudUrl").value.replace(/\s+/g,""),key=document.getElementById("cloudKey").value.replace(/\s+/g,"");localStorage.setItem(CONFIG_KEY,JSON.stringify({url:url,key:key}));toast("Configuração salva. Recarregando…");setTimeout(function(){location.reload();},500);};
var loginBtn=document.getElementById("cloudLogin");if(loginBtn)loginBtn.onclick=function(){var email=document.getElementById("cloudEmail").value.replace(/^\s+|\s+$/g,""),password=document.getElementById("cloudPassword").value;if(!email||!password){toast("Informe e-mail e senha.");return;}setCloudState("syncing","Entrando…",email);login(email,password,function(err){if(err){setCloudState("error","Falha no login",err.message);toast(err.message);return;}toast("Login realizado.");setCloudState("syncing","Conectado • sincronizando",email);reconcile();});};
var signupBtn=document.getElementById("cloudSignup");if(signupBtn)signupBtn.onclick=function(){var email=document.getElementById("cloudEmail").value.replace(/^\s+|\s+$/g,""),password=document.getElementById("cloudPassword").value;if(!email||password.length<6){toast("Use e-mail válido e senha com pelo menos 6 caracteres.");return;}signup(email,password,function(err,data){if(err){toast(err.message);return;}if(data&&data.access_token){toast("Conta criada e conectada.");reconcile();}else toast("Conta criada. Confirme o e-mail, se solicitado.");});};
var logout=document.getElementById("cloudLogout");if(logout)logout.onclick=function(){authSave(null);showAuthUI();setCloudState("local","Nuvem pronta","Sessão encerrada.");toast("Você saiu da nuvem.");};
var syncNow=document.getElementById("cloudSyncNow");if(syncNow)syncNow.onclick=function(){pushCloud(function(ok){if(ok)toast("Sincronizado.");});};
var pull=document.getElementById("cloudPull");if(pull)pull.onclick=forcePull;
window.addEventListener("online",function(){if(user()){setCloudState("syncing","Internet voltou • sincronizando",user().email||"");reconcile();}});
window.addEventListener("offline",function(){if(user())setCloudState("offline","Offline","Alterações ficam salvas neste aparelho.");});
document.addEventListener("visibilitychange",function(){if(document.visibilityState==="visible"&&user()&&navigator.onLine!==false)reconcile();});
})();